[project]
name = "swoyo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "logging>=0.4.9.6",
    "pytest>=8.3.5",
    "toml>=0.10.2",
]
